import { Metadata, type Viewport } from "next";

export const defaultSEOdata: Metadata = {
  title: "Asikur Rahman - Full-Stack Web Developer Portfolio",
  description:
    "Welcome to the portfolio of Asikur Rahman, a passionate and dedicated full-stack web developer with extensive experience in creating scalable and high-performance web applications. Specializing in modern web technologies, including Next.js, React, TypeScript, Express, Nest.js, and Docker, Asikur leverages a strong foundation in both frontend and backend development to deliver innovative solutions that meet clients' needs. With expertise in databases such as PostgreSQL and MongoDB, Asikur ensures data integrity and scalability in every project. Explore the showcased projects and discover how Asikur combines creativity and technical skills to build engaging user experiences and robust applications. Whether you are looking for a talented developer to bring your ideas to life or seeking inspiration for your own projects, Asikur's portfolio highlights a commitment to excellence and a passion for continuous learning in the fast-evolving world of web development.",
  keywords: [
    "Asikur Rahman",
    "Asikur Rahaman",
    "Ashikur Rahaman",
    "Asikur Rahman Portfolio",
    "Asikur Rahman Full-Stack Web Developer Portfolio",
    "Asikur Rahman Full-Stack Web Developer",
    "Ashiqur Rahman",
    "Ashiqur Rahman Portfolio",
    "Ashikur Rahman Full-Stack Web Developer Portfolio",
    "Ashikur Rahman Full-Stack Web Developer",
    "Ashikur Rahaman",
    "web developer",
    "full-stack developer",
    "Next.js",
    "React",
    "TypeScript",
    "portfolio",
    "JavaScript",
    "software engineer",
    "web development",
    "nextjs",
    "react",
    "typescript",
    "tailwindcss",
    "portfolio website",
    "asikur-portfolio.vercel.app",
    "best web developer",
    "best portfolio website",
    "best developer portfolio",
    "best web developer portfolio website",
    "best developer portfolio website",
    "best portfolio developer",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "aws cloud",
  ],
  openGraph: {
    title: "Asikur Rahman - Full-Stack Web Developer Portfolio",
    description:
      "Explore the portfolio of Asikur Rahman, showcasing skills in modern web technologies and innovative solutions.",
    url: "https://asikur.vercel.app",
    images: [
      {
        url: "https://res.cloudinary.com/asikur/image/upload/c_thumb,w_200,g_face/v1697458521/Screenshot_502_vzrohp.png",
        width: 1200,
        height: 630,
      },
    ],
    siteName: "Asikur Rahman Portfolio",
    locale: "en_US",
    type: "website",
  },
  twitter: {
    title: "Asikur Rahman - Full-Stack Web Developer Portfolio",
    description: "Explore my portfolio showcasing web development expertise.",
    card: "summary_large_image",
    site: "@asikur_rahman",
    creator: "@asikur_rahman",
  },
  appleWebApp: {
    title: "Asikur Rahman Portfolio",
    capable: true,
    statusBarStyle: "default",
  },
  facebook: {
    appId: "123456789",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: "all",
  },
  icons: [
    {
      url: "/icons/logo-icon.png",
      type: "image/png",
      sizes: "512x512",
    },
  ],
  applicationName: "Asikur Rahman Portfolio",
  authors: [{ name: "Asikur Rahman", url: "https://asikur.vercel.app" }],
  verification: {
    google: "google-site-verification=1234567890",
    yandex: "yandex-verification=1234567890",
    yahoo: "y_key=1234567890",
  },
  manifest: "https://asikur.vercel.app/manifest.webmanifest",
  appLinks: {
    web: [{ url: "https://asikur.vercel.app", should_fallback: true }],
  },
  creator: "Asikur Rahman",
  category: "Portfolio",
};

// Default viewport data
export const defaultViewPort: Viewport = {
  width: "device-width",
  height: "device-height",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
  colorScheme: "light",
  themeColor: "#ffffff",
  minimumScale: 1,
  interactiveWidget: "resizes-content",
};
